version: '3.3'

volumes:
  backend_static:
  backend_media:
  postgres_data:

services:

  db:    
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build: ../frontend/
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    build: ../backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/

  nginx:
    image: nginx:1.19.3
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - backend_static:/app/static/
      - backend_media:/app/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
