version: '3.3'

volumes:
  backend_static:
  backend_media:
  postgres_data:

services:

  db:    
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
    ports:
      - "5432:5432"

  frontend:
    image: kirillshirokov/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    image: kirillshirokov/foodgram_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.comf.template
      - ../frontend/build:/usr/share/nginx/html/
      - backend_static:/app/static/
      - backend_media:/app/media/
      - ../docs/:/usr/share/nginx/html/api/docs/

    depends_on:
      - backend
      - frontend
