version: '3.3'

volumes:
  backend_static:
  backend_media:
  postgres_data:

services:  
  db:    
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  frontend:
    image: kirillshirokov/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ../frontend/:/app/result_build/
  backend:
    image: kirillshirokov/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/backend_static/
      - backend_media:/app/backend_media/
    ports:
      - "80:80"
  nginx:
    image: nginx:1.19.3
    ports:
      - "8090:80"
    volumes:
      # - ../nginx/nginx.conf:/etc/nginx/sites-enabled/default
      # - ../frontend/build:/usr/share/nginx/html/
      - backend_static:/app/backend_static/
      - backend_media:/app/backend_media/
      # - ../docs/:/usr/share/nginx/html/api/docs/
